"""advertising statistics import

Revision ID: 020b4d2e32f4
Revises: 052a49c37040
Create Date: 2026-09-03 15:39:53.175595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '020b4d2e32f4'
down_revision: Union[str, None] = '052a49c37040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('ozon_sku', sa.String(length=64), nullable=False),
    sa.Column('ozon_campaign_id', sa.String(length=128), nullable=False),
    sa.Column('ad_tool', sa.String(length=100), nullable=True),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('spend_rub', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sales_promo_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=True),
    sa.Column('sales_promo_model_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('units_sold_model', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('cart_additions', sa.Integer(), nullable=True),
    sa.Column('cart_conversion_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('drr_promo_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('drr_total_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('cost_per_order_rub_ozon', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('avg_cpc_rub_ozon', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ozon_sku', 'ozon_campaign_id', 'period_start', 'period_end', name='uq_ad_stat_store_sku_campaign_period')
    )
    op.create_index(op.f('ix_advertising_statistics_campaign_id'), 'advertising_statistics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_ozon_campaign_id'), 'advertising_statistics', ['ozon_campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_ozon_sku'), 'advertising_statistics', ['ozon_sku'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_period_end'), 'advertising_statistics', ['period_end'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_period_start'), 'advertising_statistics', ['period_start'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_product_id'), 'advertising_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_advertising_statistics_store_id'), 'advertising_statistics', ['store_id'], unique=False)
    op.drop_index('ix_advertising_daily_metrics_campaign_id', table_name='advertising_daily_metrics')
    op.drop_index('ix_advertising_daily_metrics_date', table_name='advertising_daily_metrics')
    op.drop_index('ix_advertising_daily_metrics_store_id', table_name='advertising_daily_metrics')
    op.drop_table('advertising_daily_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_daily_metrics',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('spend_rub', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], name='advertising_daily_metrics_campaign_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='advertising_daily_metrics_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='advertising_daily_metrics_pkey')
    )
    op.create_index('ix_advertising_daily_metrics_store_id', 'advertising_daily_metrics', ['store_id'], unique=False)
    op.create_index('ix_advertising_daily_metrics_date', 'advertising_daily_metrics', ['date'], unique=False)
    op.create_index('ix_advertising_daily_metrics_campaign_id', 'advertising_daily_metrics', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_advertising_statistics_store_id'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_product_id'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_period_start'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_period_end'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_ozon_sku'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_ozon_campaign_id'), table_name='advertising_statistics')
    op.drop_index(op.f('ix_advertising_statistics_campaign_id'), table_name='advertising_statistics')
    op.drop_table('advertising_statistics')
    # ### end Alembic commands ###
