"""advertising campaigns architecture

Revision ID: 052a49c37040
Revises: 5e49bf5a5400
Create Date: 2026-09-03 15:14:58.373015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '052a49c37040'
down_revision: Union[str, None] = '5e49bf5a5400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic's autogenerate does not detect new values on an existing native
    # Postgres ENUM type — must add it explicitly, or SyncSourceType.OZON_ADVERTISING_API
    # fails at INSERT time with "invalid input value for enum sync_source_type".
    # SQLAlchemy's Enum() column type stores the Python enum *member name*
    # (e.g. "OZON_API"), not its .value, matching the existing labels below.
    op.execute("ALTER TYPE sync_source_type ADD VALUE IF NOT EXISTS 'OZON_ADVERTISING_API'")
    op.add_column('advertising_campaigns', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('advertising_campaigns', sa.Column('daily_budget_rub', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('advertising_campaigns', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('advertising_campaigns', sa.Column('date_to', sa.Date(), nullable=True))
    op.add_column('advertising_campaigns', sa.Column('raw_payload', sa.Text(), nullable=True))
    op.alter_column('advertising_campaigns', 'ozon_campaign_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_index(op.f('ix_advertising_campaigns_state'), 'advertising_campaigns', ['state'], unique=False)
    op.create_unique_constraint('uq_campaign_store_ozon_id', 'advertising_campaigns', ['store_id', 'ozon_campaign_id'])
    op.add_column('ozon_credentials', sa.Column('performance_last_connection_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ozon_credentials', sa.Column('performance_last_connection_ok', sa.Boolean(), nullable=True))
    op.add_column('ozon_credentials', sa.Column('performance_last_connection_message', sa.String(length=500), nullable=True))
    op.alter_column('ozon_credentials', 'client_id_encrypted',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('ozon_credentials', 'api_key_encrypted',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # server_default='0' so this doesn't fail against existing sync_runs rows;
    # the ORM model itself uses an application-level default, not a DB one.
    op.add_column('sync_runs', sa.Column('items_fetched', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_runs', sa.Column('items_created', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sync_runs', sa.Column('items_skipped_duplicate', sa.Integer(), nullable=False, server_default='0'))
    op.execute("UPDATE sync_runs SET items_fetched = reviews_fetched, items_created = reviews_created, "
               "items_skipped_duplicate = reviews_skipped_duplicate")
    op.alter_column('sync_runs', 'items_fetched', server_default=None)
    op.alter_column('sync_runs', 'items_created', server_default=None)
    op.alter_column('sync_runs', 'items_skipped_duplicate', server_default=None)
    op.drop_column('sync_runs', 'reviews_created')
    op.drop_column('sync_runs', 'reviews_skipped_duplicate')
    op.drop_column('sync_runs', 'reviews_fetched')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('reviews_fetched', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('sync_runs', sa.Column('reviews_skipped_duplicate', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('sync_runs', sa.Column('reviews_created', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.execute("UPDATE sync_runs SET reviews_fetched = items_fetched, reviews_created = items_created, "
               "reviews_skipped_duplicate = items_skipped_duplicate")
    op.alter_column('sync_runs', 'reviews_fetched', server_default=None)
    op.alter_column('sync_runs', 'reviews_created', server_default=None)
    op.alter_column('sync_runs', 'reviews_skipped_duplicate', server_default=None)
    op.drop_column('sync_runs', 'items_skipped_duplicate')
    op.drop_column('sync_runs', 'items_created')
    op.drop_column('sync_runs', 'items_fetched')
    op.alter_column('ozon_credentials', 'api_key_encrypted',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('ozon_credentials', 'client_id_encrypted',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('ozon_credentials', 'performance_last_connection_message')
    op.drop_column('ozon_credentials', 'performance_last_connection_ok')
    op.drop_column('ozon_credentials', 'performance_last_connection_check_at')
    op.drop_constraint('uq_campaign_store_ozon_id', 'advertising_campaigns', type_='unique')
    op.drop_index(op.f('ix_advertising_campaigns_state'), table_name='advertising_campaigns')
    op.alter_column('advertising_campaigns', 'ozon_campaign_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('advertising_campaigns', 'raw_payload')
    op.drop_column('advertising_campaigns', 'date_to')
    op.drop_column('advertising_campaigns', 'date_from')
    op.drop_column('advertising_campaigns', 'daily_budget_rub')
    op.drop_column('advertising_campaigns', 'state')
    # ### end Alembic commands ###
