"""accrual daily: add confirmed commission_ozon_rub column

Revision ID: 4e0b54059fd2
Revises: 6de5f9edc39a
Create Date: 2026-09-14 02:43:01.403172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e0b54059fd2'
down_revision: Union[str, None] = '6de5f9edc39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accrual_daily_statistics',
        sa.Column('commission_ozon_rub', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('accrual_daily_statistics', 'commission_ozon_rub', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accrual_daily_statistics', 'commission_ozon_rub')
    # ### end Alembic commands ###
