"""search query analytics

Revision ID: 580d61c0cc99
Revises: 70c902793203
Create Date: 2026-09-04 02:33:49.565418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '580d61c0cc99'
down_revision: Union[str, None] = '70c902793203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('ozon_sku', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('people_searched', sa.Integer(), nullable=True),
    sa.Column('people_saw', sa.Integer(), nullable=True),
    sa.Column('ordered_units_by_query', sa.Integer(), nullable=True),
    sa.Column('ordered_sum_by_query_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('position_ozon', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('conv_search_to_card_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_search_to_order_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ozon_sku', 'query_text', 'period_start', 'period_end', name='uq_search_query_stat_store_sku_query_period')
    )
    op.create_index(op.f('ix_search_query_statistics_ozon_sku'), 'search_query_statistics', ['ozon_sku'], unique=False)
    op.create_index(op.f('ix_search_query_statistics_period_end'), 'search_query_statistics', ['period_end'], unique=False)
    op.create_index(op.f('ix_search_query_statistics_period_start'), 'search_query_statistics', ['period_start'], unique=False)
    op.create_index(op.f('ix_search_query_statistics_product_id'), 'search_query_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_search_query_statistics_query_text'), 'search_query_statistics', ['query_text'], unique=False)
    op.create_index(op.f('ix_search_query_statistics_store_id'), 'search_query_statistics', ['store_id'], unique=False)
    op.drop_index('ix_search_queries_date', table_name='search_queries')
    op.drop_index('ix_search_queries_product_id', table_name='search_queries')
    op.drop_index('ix_search_queries_store_id', table_name='search_queries')
    op.drop_table('search_queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='search_queries_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='search_queries_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search_queries_pkey')
    )
    op.create_index('ix_search_queries_store_id', 'search_queries', ['store_id'], unique=False)
    op.create_index('ix_search_queries_product_id', 'search_queries', ['product_id'], unique=False)
    op.create_index('ix_search_queries_date', 'search_queries', ['date'], unique=False)
    op.drop_index(op.f('ix_search_query_statistics_store_id'), table_name='search_query_statistics')
    op.drop_index(op.f('ix_search_query_statistics_query_text'), table_name='search_query_statistics')
    op.drop_index(op.f('ix_search_query_statistics_product_id'), table_name='search_query_statistics')
    op.drop_index(op.f('ix_search_query_statistics_period_start'), table_name='search_query_statistics')
    op.drop_index(op.f('ix_search_query_statistics_period_end'), table_name='search_query_statistics')
    op.drop_index(op.f('ix_search_query_statistics_ozon_sku'), table_name='search_query_statistics')
    op.drop_table('search_query_statistics')
    # ### end Alembic commands ###
