"""initial schema

Revision ID: 5e49bf5a5400
Revises: 
Create Date: 2026-09-03 14:20:37.833991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e49bf5a5400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('advertising_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('ozon_campaign_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertising_campaigns_ozon_campaign_id'), 'advertising_campaigns', ['ozon_campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_campaigns_store_id'), 'advertising_campaigns', ['store_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_store_id'), 'audit_log', ['store_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('ozon_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('client_id_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('performance_client_id_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('performance_client_secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('last_connection_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connection_ok', sa.Boolean(), nullable=True),
    sa.Column('last_connection_message', sa.String(length=500), nullable=True),
    sa.Column('reviews_api_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ozon_credentials_store_id'), 'ozon_credentials', ['store_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('ozon_sku', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ozon_sku', name='uq_product_store_sku')
    )
    op.create_index(op.f('ix_products_ozon_sku'), 'products', ['ozon_sku'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('store_ai_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('tone_of_voice', sa.String(length=50), nullable=False),
    sa.Column('customer_address_form', sa.String(length=50), nullable=False),
    sa.Column('reply_length', sa.String(length=20), nullable=False),
    sa.Column('use_emoji', sa.Boolean(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('forbidden_words', sa.Text(), nullable=True),
    sa.Column('allowed_promises', sa.Text(), nullable=True),
    sa.Column('negative_review_rules', sa.Text(), nullable=True),
    sa.Column('warranty_info', sa.Text(), nullable=True),
    sa.Column('return_policy_info', sa.Text(), nullable=True),
    sa.Column('support_contacts', sa.Text(), nullable=True),
    sa.Column('product_facts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_ai_settings_store_id'), 'store_ai_settings', ['store_id'], unique=True)
    op.create_table('store_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'VIEWER', name='store_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='uq_membership_user_store')
    )
    op.create_index(op.f('ix_store_memberships_store_id'), 'store_memberships', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_memberships_user_id'), 'store_memberships', ['user_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('OZON_API', 'CSV_IMPORT', 'XLSX_IMPORT', name='sync_source_type'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='sync_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviews_fetched', sa.Integer(), nullable=False),
    sa.Column('reviews_created', sa.Integer(), nullable=False),
    sa.Column('reviews_skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_store_id'), 'sync_runs', ['store_id'], unique=False)
    op.create_table('advertising_daily_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spend_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertising_daily_metrics_campaign_id'), 'advertising_daily_metrics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_daily_metrics_date'), 'advertising_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_advertising_daily_metrics_store_id'), 'advertising_daily_metrics', ['store_id'], unique=False)
    op.create_table('change_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.Enum('MAIN_PHOTO', 'SEO', 'TITLE', 'DESCRIPTION', 'PRICE', 'CHARACTERISTICS', 'ADVERTISING', 'OTHER', name='change_type'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_history_product_id'), 'change_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_change_history_store_id'), 'change_history', ['store_id'], unique=False)
    op.create_table('product_daily_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('revenue_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_daily_metrics_date'), 'product_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_product_daily_metrics_product_id'), 'product_daily_metrics', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_daily_metrics_store_id'), 'product_daily_metrics', ['store_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('PRODUCT_IMPROVEMENT', 'CARD_IMPROVEMENT', 'INFOGRAPHIC_IDEA', 'GENERAL', name='recommendation_kind'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_review_ids_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_store_id'), 'recommendations', ['store_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('ozon_review_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.Enum('OZON_API', 'CSV_IMPORT', 'XLSX_IMPORT', 'DEMO', name='review_source'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('existing_seller_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PENDING_ANALYSIS', 'ANALYZED', 'DRAFT_CREATED', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'PUBLISH_FAILED', 'NO_REPLY_NEEDED', name='review_status'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ozon_review_id', name='uq_review_store_ozon_id')
    )
    op.create_index(op.f('ix_reviews_ozon_review_id'), 'reviews', ['ozon_review_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_store_id'), 'reviews', ['store_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_date'), 'search_queries', ['date'], unique=False)
    op.create_index(op.f('ix_search_queries_product_id'), 'search_queries', ['product_id'], unique=False)
    op.create_index(op.f('ix_search_queries_store_id'), 'search_queries', ['store_id'], unique=False)
    op.create_table('ai_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_rub', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_review_id'), 'ai_generations', ['review_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_store_id'), 'ai_generations', ['store_id'], unique=False)
    op.create_table('review_ai_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('reply_needed', sa.Boolean(), nullable=False),
    sa.Column('advantages_json', sa.Text(), nullable=True),
    sa.Column('complaints_json', sa.Text(), nullable=True),
    sa.Column('product_improvements_json', sa.Text(), nullable=True),
    sa.Column('card_improvements_json', sa.Text(), nullable=True),
    sa.Column('hypotheses_json', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_ai_analysis_review_id'), 'review_ai_analysis', ['review_id'], unique=True)
    op.create_index(op.f('ix_review_ai_analysis_store_id'), 'review_ai_analysis', ['store_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', 'PUBLISH_FAILED', name='comment_status'), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=64), nullable=True),
    sa.Column('published_via', sa.String(length=20), nullable=True),
    sa.Column('ozon_comment_id', sa.String(length=128), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_comments_store_id'), 'review_comments', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_store_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_ai_analysis_store_id'), table_name='review_ai_analysis')
    op.drop_index(op.f('ix_review_ai_analysis_review_id'), table_name='review_ai_analysis')
    op.drop_table('review_ai_analysis')
    op.drop_index(op.f('ix_ai_generations_store_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_review_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_search_queries_store_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_product_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_date'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_reviews_store_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_ozon_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recommendations_store_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_product_daily_metrics_store_id'), table_name='product_daily_metrics')
    op.drop_index(op.f('ix_product_daily_metrics_product_id'), table_name='product_daily_metrics')
    op.drop_index(op.f('ix_product_daily_metrics_date'), table_name='product_daily_metrics')
    op.drop_table('product_daily_metrics')
    op.drop_index(op.f('ix_change_history_store_id'), table_name='change_history')
    op.drop_index(op.f('ix_change_history_product_id'), table_name='change_history')
    op.drop_table('change_history')
    op.drop_index(op.f('ix_advertising_daily_metrics_store_id'), table_name='advertising_daily_metrics')
    op.drop_index(op.f('ix_advertising_daily_metrics_date'), table_name='advertising_daily_metrics')
    op.drop_index(op.f('ix_advertising_daily_metrics_campaign_id'), table_name='advertising_daily_metrics')
    op.drop_table('advertising_daily_metrics')
    op.drop_index(op.f('ix_sync_runs_store_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_store_memberships_user_id'), table_name='store_memberships')
    op.drop_index(op.f('ix_store_memberships_store_id'), table_name='store_memberships')
    op.drop_table('store_memberships')
    op.drop_index(op.f('ix_store_ai_settings_store_id'), table_name='store_ai_settings')
    op.drop_table('store_ai_settings')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_ozon_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ozon_credentials_store_id'), table_name='ozon_credentials')
    op.drop_table('ozon_credentials')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_store_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_advertising_campaigns_store_id'), table_name='advertising_campaigns')
    op.drop_index(op.f('ix_advertising_campaigns_ozon_campaign_id'), table_name='advertising_campaigns')
    op.drop_table('advertising_campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stores')
    # ### end Alembic commands ###
