"""accrual daily statistics (true-daily total, /v1/finance/accrual/by-day)

Revision ID: 6de5f9edc39a
Revises: ce0c75985ad9
Create Date: 2026-09-14 01:42:26.326755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6de5f9edc39a'
down_revision: Union[str, None] = 'ce0c75985ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accrual_daily_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('by_category_json', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', name='uq_accrual_daily_store_date')
    )
    op.create_index(op.f('ix_accrual_daily_statistics_store_id'), 'accrual_daily_statistics', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accrual_daily_statistics_store_id'), table_name='accrual_daily_statistics')
    op.drop_table('accrual_daily_statistics')
    # ### end Alembic commands ###
