"""product card analytics

Revision ID: 70c902793203
Revises: 020b4d2e32f4
Create Date: 2026-09-04 01:55:26.930683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '70c902793203'
down_revision: Union[str, None] = '020b4d2e32f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_card_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('ozon_sku', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('category_l1', sa.String(length=255), nullable=True),
    sa.Column('category_l2', sa.String(length=255), nullable=True),
    sa.Column('category_l3', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_scheme', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions_total', sa.Integer(), nullable=True),
    sa.Column('impressions_search_catalog', sa.Integer(), nullable=True),
    sa.Column('card_visits', sa.Integer(), nullable=True),
    sa.Column('cart_adds_from_search_catalog', sa.Integer(), nullable=True),
    sa.Column('cart_adds_from_card', sa.Integer(), nullable=True),
    sa.Column('cart_adds_total', sa.Integer(), nullable=True),
    sa.Column('ordered_units', sa.Integer(), nullable=True),
    sa.Column('delivered_units', sa.Integer(), nullable=True),
    sa.Column('bought_out_units', sa.Integer(), nullable=True),
    sa.Column('cancelled_units_by_cancel_date', sa.Integer(), nullable=True),
    sa.Column('cancelled_units_by_order_date', sa.Integer(), nullable=True),
    sa.Column('returned_units_by_return_date', sa.Integer(), nullable=True),
    sa.Column('returned_units_by_order_date', sa.Integer(), nullable=True),
    sa.Column('ordered_sum_actual_price_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ordered_sum_list_price_rub', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('search_catalog_position_ozon', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('conv_impression_to_order_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_search_catalog_to_cart_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_search_catalog_to_card_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_card_to_cart_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_to_cart_total_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_cart_to_order_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('conv_order_to_buyout_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('avg_price_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_from_median_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('price_index_label_ozon', sa.String(length=50), nullable=True),
    sa.Column('promo_days_label_ozon', sa.String(length=20), nullable=True),
    sa.Column('paid_promo_days_label_ozon', sa.String(length=20), nullable=True),
    sa.Column('drr_pct_ozon', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('stock_end_of_period', sa.Integer(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('abc_by_revenue_ozon', sa.String(length=1), nullable=True),
    sa.Column('abc_by_units_ozon', sa.String(length=1), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ozon_sku', 'date', name='uq_card_stat_store_sku_date')
    )
    op.create_index(op.f('ix_product_card_statistics_date'), 'product_card_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_product_card_statistics_ozon_sku'), 'product_card_statistics', ['ozon_sku'], unique=False)
    op.create_index(op.f('ix_product_card_statistics_product_id'), 'product_card_statistics', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_card_statistics_store_id'), 'product_card_statistics', ['store_id'], unique=False)
    op.drop_index('ix_product_daily_metrics_date', table_name='product_daily_metrics')
    op.drop_index('ix_product_daily_metrics_product_id', table_name='product_daily_metrics')
    op.drop_index('ix_product_daily_metrics_store_id', table_name='product_daily_metrics')
    op.drop_table('product_daily_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_daily_metrics',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue_rub', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_daily_metrics_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='product_daily_metrics_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_daily_metrics_pkey')
    )
    op.create_index('ix_product_daily_metrics_store_id', 'product_daily_metrics', ['store_id'], unique=False)
    op.create_index('ix_product_daily_metrics_product_id', 'product_daily_metrics', ['product_id'], unique=False)
    op.create_index('ix_product_daily_metrics_date', 'product_daily_metrics', ['date'], unique=False)
    op.drop_index(op.f('ix_product_card_statistics_store_id'), table_name='product_card_statistics')
    op.drop_index(op.f('ix_product_card_statistics_product_id'), table_name='product_card_statistics')
    op.drop_index(op.f('ix_product_card_statistics_ozon_sku'), table_name='product_card_statistics')
    op.drop_index(op.f('ix_product_card_statistics_date'), table_name='product_card_statistics')
    op.drop_table('product_card_statistics')
    # ### end Alembic commands ###
