"""realization report months (Ozon official monthly settlement, /v2/finance/realization)

Revision ID: ce0c75985ad9
Revises: a7d4e1c8f5b2
Create Date: 2026-09-13 06:23:14.598287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce0c75985ad9'
down_revision: Union[str, None] = 'a7d4e1c8f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realization_report_months',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'year', 'month', name='uq_realization_report_store_year_month')
    )
    op.create_index(op.f('ix_realization_report_months_store_id'), 'realization_report_months', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_realization_report_months_store_id'), table_name='realization_report_months')
    op.drop_table('realization_report_months')
    # ### end Alembic commands ###
